---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flagger-loadtester
  namespace: dev
spec:
  interval: 6h
  ref:
    semver: 1.x
  verify: # verify the artifact signature with Cosign keyless
    provider: cosign
  url: oci://ghcr.io/fluxcd/flagger-manifests
